In [1]:
import numpy as np

- 임의의 값으로 (3,2) 형태의 ndarray를 생성할 것

In [4]:
#파이선 랜덤
import random
#0,1 미만 사이의 랜덤값
print(random.random())
#1-6 사이 중 랜덤값 
print(random.randrange(1,7))



0.7492350079141129
3


In [5]:
#0-1 균등분포 

np.random.rand(2,3,4)

array([[[0.55200649, 0.14308   , 0.8125405 , 0.61655882],
        [0.11236731, 0.83920284, 0.46296291, 0.66540336],
        [0.88765773, 0.93653927, 0.35524703, 0.40254479]],

       [[0.22867621, 0.3898121 , 0.42545695, 0.1361749 ],
        [0.73140627, 0.25619175, 0.96951681, 0.59121132],
        [0.571015  , 0.99923692, 0.11228051, 0.12917553]]])

In [6]:
# 정규분포 

np.random.randn(5)

array([-0.56132004,  2.11313053, -0.45915721,  1.32840803,  0.75584849])

In [14]:
# 0~2 사이의 숫자를 랜덤으로 뽑고 크기가 5
a =np.random.randint(3, size=5)
# 3~9 사이의 숫자를 랜덤으로 뽑고 크키가 5
b =np.random.randint(3,10, size =5)
print(a)
print(b)


[2 2 0 0 2]
[9 9 7 7 5]


In [21]:
#3~9까지의 숫자를 랜덤으로 뽑고 배열의 크기가 행3열5
np.random.randint(3,10, size =(3,5))

array([[7, 7, 4, 8, 7],
       [8, 4, 6, 3, 6],
       [7, 8, 6, 4, 9]])

In [25]:
#seed -> 랜덤으로 뽑지만 동일한 값
#seed() 의 파라미터 값이 바뀌면 다른 숫자가 나오지만 같은 값을 넣으면 계속 같은 값만 나옴  
np.random.seed(25)
arr = np.random.randn(2,3)
print(arr)

[[ 0.22827309  1.0268903  -0.83958485]
 [-0.59118152 -0.9568883  -0.22232569]]


In [24]:
np.random.seed(20)
arr = np.random.randn(2,3)
print(arr)

[[ 0.88389311  0.19586502  0.35753652]
 [-2.34326191 -1.08483259  0.55969629]]


In [44]:
#0~5미만의 수 중 3개를 랜덤 추출 , true: 중복 허용 
np.random.choice(5,3,True)

array([2, 4, 4])

In [45]:
#0~5 미만의 수 중 3개를 랜덤 추출 , false: 중복 비허용
np.random.choice(5,3,False)

array([4, 2, 1])

- 임의의 값으로 (3,2) 형태의 ndarray를 생성할 것 
    - 단 같은 조는 동일한 값이 나와야 함

In [48]:
np.random.seed(20)
arr = np.random.randn(2,3)
print(arr)

[[ 0.88389311  0.19586502  0.35753652]
 [-2.34326191 -1.08483259  0.55969629]]


In [53]:
# 1차원 12개 항목
arr = np.arange(12)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [59]:
#2차원 3개의 행과 4개의 열
arr2= arr.reshape(3,4)
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [61]:
#2차원
arr3=arr.reshape(4,3)
arr4=arr.reshape(6,2)
print(arr3)
print("--------")
print(arr4)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [65]:
#3차원
arr5=arr.reshape(2,3,2)
print(arr5.shape)
print(arr5.ndim)
print(arr5)

(2, 3, 2)
3
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [67]:
# 행을 정해주면 (3) 나머지 숫자로 알아서 열을 만듦
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
arr6= np.arange(12).reshape(2,3,2)
print(arr6)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [70]:
#1차원 배열로 바꿈 
arr6.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])