인덱싱
- 단일 값: 인덱스를 이용하여 하나의 데이터에 접근
- 슬라이싱: 연속된 인덱스를 이용하여 여러 데이터에 접근
- 팬시 인덱싱: 리스트 형태의 인덱스를 이용하여 여러 데이터에 접근
- 불린 인덱싱: 불링값의 리스트 형태의 인덱스를 이용하여 여러 데이터에 접근 

In [1]:
import numpy as np

arr = np.arange(1, 11)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [2]:
arr[5]

6

In [3]:
#1~10미만의 배열 만들고 이것을 reshape()  함수로 행이 3인 것으로 만들기 
arr = np.arange(1,10).reshape(3,-1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[0][0]

1

In [6]:
arr[0,0]

1

In [7]:
arr[2,1]

8

In [8]:
arr1 = np.arange(1,9).reshape(2,2,2)
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(arr1[0])

[[1 2]
 [3 4]]


In [10]:
print(arr1[0,0])

[1 2]


In [11]:
print(arr1[0,0,0])

1


In [12]:
print(arr1[1,1,0])

7


In [13]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
#끝에서 부터 
arr[-1]

10

In [15]:
arr[-3]

8

In [16]:
arr=np.arange(1,9).reshape(2,2,2)
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
arr[0,1,-1]

4

In [18]:
# 슬라이싱

In [19]:
arr = np.arange(1,11)
print(arr)
arr[1:5]

[ 1  2  3  4  5  6  7  8  9 10]


array([2, 3, 4, 5])

In [20]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[:-2]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr = np.arange(1,10).reshape(3,-1)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(arr[0:1,0:1])

[[1]]


In [25]:
print(arr[1:2, 0:2])

[[4 5]]


- 5,6 / 8,9 가져오기

In [26]:
print(arr[1:3, 1:3])

[[5 6]
 [8 9]]


In [27]:
print(arr[1:,1:])

[[5 6]
 [8 9]]


In [28]:
arr = np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [29]:
print(arr[0:2, 0:2,0:2])

[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]]


In [30]:
a= arr[2:3, :, 0:2]
print(a)

[[[19 20]
  [22 23]
  [25 26]]]


In [31]:
b=arr[2, :, 0:2]
print(b)

[[19 20]
 [22 23]
 [25 26]]


In [32]:
print(a.ndim)
print(b.ndim)

3
2


In [33]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
print(arr[[1,5]])
print(arr[[1]])

[2 6]
[2]


In [35]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
#불린 인덱싱

#조건
mask_1 = arr > 3
print(mask_1)
print(type(mask_1))
print(mask_1.shape)

[False False False  True  True  True  True  True  True  True]
<class 'numpy.ndarray'>
(10,)


In [37]:
arr[mask_1]

array([ 4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [39]:
mask_2 = (arr > 3) & (arr<7)

In [40]:
arr[mask_2]

array([4, 5, 6])

In [41]:
mask_3 = arr >3

print(arr[mask_3])
print(type(arr[mask_3]))
print(arr[mask_3].shape)

[ 4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(7,)


In [42]:
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])

연산
- add
- substract
- multiply
- divide

In [43]:
arr1=np.arange(1,11).reshape(2,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
arr1.shape

(2, 5)

In [45]:
arr2 = np.random.randint(1,10, size=10).reshape(2,5)
print(arr2)

[[4 5 8 6 9]
 [9 5 1 3 9]]


In [46]:
np.add(arr1, arr2)

array([[ 5,  7, 11, 10, 14],
       [15, 12,  9, 12, 19]])

In [47]:
arr3 = arr2.reshape(5,2)
arr3

array([[4, 5],
       [8, 6],
       [9, 9],
       [5, 1],
       [3, 9]])

In [51]:
np.subtract(arr1,arr2)

array([[-3, -3, -5, -2, -4],
       [-3,  2,  7,  6,  1]])

In [52]:
np.multiply(arr1, arr2)

array([[ 4, 10, 24, 24, 45],
       [54, 35,  8, 27, 90]])

In [53]:
np.divide(arr1, arr2)

array([[0.25      , 0.4       , 0.375     , 0.66666667, 0.55555556],
       [0.66666667, 1.4       , 8.        , 3.        , 1.11111111]])

In [54]:
arr2

array([[4, 5, 8, 6, 9],
       [9, 5, 1, 3, 9]])

브로드 캐스팅

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bc_arr = arr1.reshape(-1)
print(bc_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
bc_arr +5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
arr1 =np.arange(3).reshape(3,1)
print(arr1)

[[0]
 [1]
 [2]]


In [67]:
arr2 =np.arange(3)
print(arr2)

[0 1 2]


In [68]:
arr1+arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [71]:
arr1 = np.random.rand(10).reshape(2,5)
print(arr1)

[[0.4722229  0.99342924 0.81977218 0.48234562 0.61506962]
 [0.43232633 0.03969698 0.63258348 0.21402501 0.82886705]]


In [72]:
#평균값
np.mean(arr1)

0.5530338411292078

In [73]:
arr1.mean()

0.5530338411292078

- max, min, argmax : 가장 큰 값의 index, argmin:가장 작은 값의 index


In [74]:
print(arr1)

[[0.4722229  0.99342924 0.81977218 0.48234562 0.61506962]
 [0.43232633 0.03969698 0.63258348 0.21402501 0.82886705]]


In [75]:
np.max(arr1)

0.9934292418062213

In [76]:
np.min(arr1)

0.03969697850279441

In [77]:
np.argmax(arr1) #argmax() : 가장 큰 값의 index

1

In [79]:
arr1.reshape(-1)[7]

0.6325834777491086

In [80]:
arr1.reshape(-1)[np.argmax(arr1)]

0.9934292418062213

median: 중앙값, std: 표준편차, var: 분산

In [81]:
np.median(arr1) #중앙값 

0.5487076164541091

In [82]:
np.var(arr1) #분산 

0.07558972546606836

In [85]:
np.std(arr1) #표준편차

0.27493585700317147

sum: 전체 합계, cumsum:누적합계

In [89]:
arr2 = np.arange(10).reshape(2,5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [90]:
np.sum(arr2)

45

In [91]:
np.cumsum(arr2)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [92]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [94]:
np.sum(arr, axis =0) #axis =0 행축 방향으로 더함 

45

In [96]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [97]:
np.sum(arr, axis=0) #axis =0 행축 방향으로 더함 

array([12, 15, 18, 21])

In [98]:
np.sum(arr, axis=1)#axis =1 열축 방향으로 더함 

array([ 6, 22, 38])

In [99]:
arr = np.arange(24).reshape(2,3,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


- axis => 0,1,2(3차원이므로 축이 3개/ 첫번째는 면축, 두번째는 행축, 세번째는 열축)
- shape(2,3,4)
- 해당하는 위치의 shape가 사라지고 나머지 형태의 shape가 남는다
- 예를 들어 axis가 0이면 shape(2,3,4) 중 첫번쨰 2가 사라지고 (3,4) 형태가 남는다 

In [100]:
print(np.sum(arr, axis=0))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [102]:
print(np.sum(arr, axis=1))

[[12 15 18 21]
 [48 51 54 57]]


In [103]:
print(np.sum(arr, axis=2))

[[ 6 22 38]
 [54 70 86]]


any, all, where

- any: 최소 하나 이상 조건을 만족하면 true, 모두 만족하지 않으면 false
- all: 모든 원소가 조건을 만족하면 true, 하나라도 만족하지 않으면 false
- where: 조건에 의해 값을 검색


In [105]:
arr= np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [108]:
np.any(arr>5)

True

In [109]:
np.all(arr>10)

False

In [110]:
arr[np.where(arr>5)]

array([ 6,  7,  8,  9, 10])

In [111]:
np.where(arr>5, True, True)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])